options:
    formatter: stylish
files:
    include: '**/*.scss'
    ignore:
      - 'node_modules/**/*'
      - '**/src/shared/styles/vendors/*'
rules:
    # Extends
    extends-before-mixins: 1
    extends-before-declarations: 1
    placeholder-in-extend: 1

    # Mixins
    mixins-before-declarations: 1

    # Line Spacing
    one-declaration-per-line: 1
    empty-line-between-blocks:
      - 0
      - ignore-single-line-rulesets: false
    single-line-per-selector: 0

    # Disallows
    no-attribute-selectors: 0
    no-color-hex: 0
    no-color-keywords: 1
    no-color-literals: 1
    no-combinators: 0
    no-css-comments: 0
    no-debug: 1
    no-disallowed-properties: 0
    no-duplicate-properties: 0
    no-empty-rulesets: 1
    no-extends: 0
    no-ids: 1
    no-important: 1
    no-invalid-hex: 1
    no-mergeable-selectors: 1
    no-misspelled-properties:
      - 1
      - extra-properties: []
    no-qualifying-elements:
      - 1
      - allow-element-with-attribute: false
        allow-element-with-class: false
        allow-element-with-id: false
    no-trailing-whitespace: 1
    no-trailing-zero: 1
    no-transition-all: 1
    no-universal-selectors: 0
    no-url-domains: 0
    no-url-protocols: 0
    no-vendor-prefixes: 1
    no-warn: 1
    property-units: 0

    # Nesting
    declarations-before-nesting: 1
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0

    # Name Formats
    class-name-format:
      - 1
      - convention: ^[a-z](_?[a-z0-9]+)*(--[a-z0-9](_?[a-z0-9]+)*)?((-[a-z0-9](_?[a-z0-9]+)*){0,2})?$
        convention-explanation: 'Class should be written in BEM (Block Element Modifier) format. e.g. block_name--elem_name-mod_name-mod_val'
    function-name-format:
      - 1
      - allow-leading-underscore: false
        convention: camelcase
    id-name-format:
      - 1
      - convention: hyphenatedlowercases
    mixin-name-format:
      - 1
      - allow-leading-underscore: false
        convention: hyphenatedlowercase
    placeholder-name-format:
      - 1
      - convention: hyphenatedlowercase
    variable-name-format:
      - 1
      - allow-leading-underscore: false
        convention: camelcase

    # Style Guide
    attribute-quotes: 1
    bem-depth: 0
    border-zero: 1
    brace-style:
       - 1
       - allow-single-line: true
    clean-import-paths:
      - 1
      - filename-extension: false
      - leading-underscore: false
    empty-args: 1
    hex-length:
      - 1
      - style: short
    hex-notation:
      - 1
      - style: lowercase
    indentation:
        - 1
        - size: 4
    leading-zero:
      - 1
      - include: false
    max-line-length: 0
    max-file-line-count: 0
    mixin-name-format:
        - 1
        - convention: camelCase
    nesting-depth:
      - 2
      - max-depth: 4
    property-sort-order:
      - 1
      - ignore-custom-properties: false
    pseudo-element: 1
    quotes:
      - 1
      - style: single
    shorthand-values: 1
    url-quotes: 1
    variable-for-property: 1
    zero-unit: 1

    # Inner Spacing
    space-after-comma: 1
    space-before-colon: 1
    space-after-colon:
      - 1
      - include: true
    space-before-brace:
      - 1
      - include: true
    space-before-bang:
      - 1
      - include: true
    space-after-bang:
      - 1
      - include: false
    space-between-parens:
      - 1
      - include: false
    space-around-operator: 1

    # Final Items
    trailing-semicolon: 1
    final-newline:
      - 1
      - include: true
